apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-boss-fight-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: angular-boss-fight.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-boss-fight
                port:
                  number: 80
